swagger: "2.0"
info:
  version: 2.4.0
  title: Koverse API
  description: >
        Koverse Web API Specification


host: koverse.swagger.io:8000

consumes:
  - application/json
produces:
  - application/json

definitions:
  dataSetMetadata:
    $ref: schemas/dataSetMetadata.yaml
  dataSetResult:
    $ref: schemas/dataSetResult.yaml
  login:
    $ref: schemas/login.yaml
  logout:
    $ref: schemas/logout.yaml
  record:
    $ref: schemas/record.yaml
  #searchAutocomplete:
  #  $ref: schemas/searchAutocomplete.yaml
  user:
    $ref: schemas/user.yaml

parameters:
  dataSetId:
    name: dataSetId
    in: path
    description: Unique identifier of the data set
    required: true
    type: string
  fileType:
    name: fileType
    in: path
    description: fileType to download
    required: false
    type: string
    enum: [json, csv]
  recordStyle:
    name: recordStyle
    in: query
    description: >
          Requests a more efficient representation of records
    required: false
    type: string
    enum: [2.2]
  objectQuery:
    name: query
    in: body
    required: true
    schema:
      $ref: schemas/objectQuery.yaml
  objectQueryNames:
    name: query
    in: body
    required: true
    schema:
      $ref: schemas/objectQueryNames.yaml
paths:
  /api/v1/datasets:
    $ref: paths/dataSets.yaml
  /api/v1/datasets/{dataSetId}:
    $ref: paths/dataSet.yaml
  /api/v1/datasets/{dataSetId}/attribute-names:
    $ref: paths/dataSetAttributeNames.yaml

# this may not belong in a web app API

#  /api/v1/dataSets/{dataSetId}/download/{fileType}:
#    $ref: paths/dataSetDownload.yaml
  /api/v1/datasets/{dataSetId}/records:
    $ref: paths/records.yaml
  /api/v1/login:
    $ref: paths/login.yaml
  /api/v1/logout:
    $ref: paths/logout.yaml
  /api/v1/query/:
    $ref: paths/queryLucene.yaml
  /api/v1/query/object:
    $ref: paths/queryObject.yaml
  /api/v1/query/object/names:
    $ref: paths/queryObjectNames.yaml
  #/api/v1/search/autocomplete:
  #  $ref: paths/searchAutocomplete.yaml
