swagger: "2.0"
info:
  version: 2.4.0
  title: Koverse API
  description: >
        Koverse Web API Specification


host: http://demo.koverse.com

consumes:
  - application/json
produces:
  - application/json

tags:
  - name: DataSets
    description: Everything about your datasets
  - name: Authentication
    description: Everything about authentication
  - name: Query
    description: Everything about your query

definitions:
  dataSetMetadata:
    $ref: schemas/dataSetMetadata.yaml
  dataSetResult:
    $ref: schemas/dataSetResult.yaml
  login:
    $ref: schemas/login.yaml
  logout:
    $ref: schemas/logout.yaml
  record:
    $ref: schemas/record.yaml
  #searchAutocomplete:
  #  $ref: schemas/searchAutocomplete.yaml
  user:
    $ref: schemas/user.yaml

parameters:
  dataSetId:
    name: dataSetId
    in: path
    description: Unique identifier of the data set
    required: true
    type: string
  fileType:
    name: fileType
    in: path
    description: fileType to download
    required: false
    type: string
    enum: [json, csv]
  recordStyle:
    name: recordStyle
    in: query
    description: >
          Requests a more efficient representation of records
    required: false
    type: string
    enum: [2.2]
  objectQuery:
    name: query
    in: body
    required: true
    schema:
      $ref: schemas/objectQuery.yaml
paths:
  /api/dataSets:
    $ref: paths/dataSets.yaml
  /api/dataSets/{dataSetId}:
    $ref: paths/dataSet.yaml
  /api/dataSets/{dataSetId}/attributeNames:
    $ref: paths/dataSetAttributeNames.yaml

# this may not belong in a web app API

#  /api/dataSets/{dataSetId}/download/{fileType}:
#    $ref: paths/dataSetDownload.yaml
  /api/dataSets/{dataSetId}/records:
    $ref: paths/records.yaml
  /api/login:
    $ref: paths/login.yaml
  /api/logout:
    $ref: paths/logout.yaml
  /api/query/:
    $ref: paths/queryLucene.yaml
  /api/query/object:
    $ref: paths/queryObject.yaml
  /api/query/object/names:
    $ref: paths/queryObjectNames.yaml
  #/api/search/autocomplete:
  #  $ref: paths/searchAutocomplete.yaml
